// Dev helper: exercise form validation, honeypot and error path, plus reduced-motion final state.
import puppeteer from "puppeteer-core";
const b = await puppeteer.launch({ executablePath: "C:/Program Files/Google/Chrome/Application/chrome.exe", headless: true });
const p = await b.newPage();
await p.setViewport({ width: 1280, height: 900 });
await p.goto("http://localhost:3001", { waitUntil: "networkidle0" });
await p.click("#request button[type=submit]");
console.log("errors:", await p.$$eval("[id$=-err]", (e) => e.map((x) => x.textContent)));
console.log("focused:", await p.evaluate(() => document.activeElement?.id));
await p.type("#name", "Test Person");
await p.type("#email", "t@example.com");
await p.type("#website", "example.com");
await p.select("#tier", "Starter");
await p.click("#request button[type=submit]");
await new Promise((r) => setTimeout(r, 1500));
console.log("after submit:", await p.$eval("#request", (e) => e.innerText.slice(-200)));
const r = await p.evaluate(() => fetch("/api/request", { method: "POST", body: JSON.stringify({ company_fax: "x" }) }).then((r) => r.json()));
console.log("honeypot:", r);
await p.emulateMediaFeatures([{ name: "prefers-reduced-motion", value: "reduce" }]);
await p.reload({ waitUntil: "networkidle0" });
await p.screenshot({ path: "../shots/reduced.png", clip: { x: 0, y: 380, width: 1280, height: 420 } });
await b.close();
